### PR TITLE
Syntax and semantic changes to work with Julia 1.1+

### PR DESCRIPTION
**Pull request by maetshju**
This PR resolves the syntactic deprecation warnings that are observed when running with Julia 0.7. It also resolves semantic errors flagged during the test cases, such as `+` not broadcasting by default with an `Array` and an `Int` anymore.

### CODE REVIEW

**Comment by maetshju** [comment]
The CI checks that aren't passing are the ones on Mac OS X because I'm using `apt` to install `matplotlib`, and `apt` isn't available on Macs. The package itself seems to be passing all tests though.

**Comment by holgerteichgraeber** [comment]
Thanks for updating @maetshju, excited for using TimeWarp.jl on julia v1 as well.

**Review by joefowler — CHANGES_REQUESTED** [review]
Thanks, @maetshju for this update! I wrote the package that @ahwillia based this on, so I believe I'm a committer here. This looks great. I have three suggestions:

1. I think the `.travis.yml:before_install` block looks like it's doing the apt installations by "brute force", but Travis supports a different, more subtle mode, `addons: apt: packages`. See a [couple of](https://github.com/usnistgov/Pope.jl/blob/master/.travis.yml) my [other projects](https://github.com/joefowler/ARMA.jl/blob/master/.travis.yml), which have blocks like the following to cover apt installs:
```text
addons:
  apt:
    packages:
    - hdf5-tools
    - libnlopt0
sudo: required
```
It's even possible that this change will make the Macintosh build work. (?)

2. If not, then I would drop the line `-osx` from the Travis CI configuration. If you check the example projects listed at the Travis [Building a Julia project](https://docs.travis-ci.com/user/languages/julia/#example-projects) page, you'll find that only 3 of the 6 even test on OS X. There's nothing in this package that ought to be different from one OS to another, so the easiest thing is not to bother.

3. Remove `Manifest.toml` from the git repository and add it to the `.gitignore` file. That's not supposed to be part of the package, if I understand Pkg3 correctly. (Let us stipulate that I do _not_ understand Pkg3 very well at all.)

Also, are you sure you even need the `.travis.yml:before` clause or my suggested replacement? Julia on Linux ought to be able to install the proper dependencies, including matplotlib, as long as the `Project.toml` file is right, shouldn't it? Because installation of matplotlib should be implied by the `PyPlot` dependency.

**Comment by maetshju** [comment]
Thanks for the feedback, @joefowler! I have rewritten the matplotlib installation as you recommended. Like you, I had thought that PyPlot.jl would set up matplotlib by itself, but it doesn't seem like it does; their README mentions installing it manually unless you can get Conda.jl set up. The [Travis CI for PyPlot.jl](https://github.com/JuliaPy/PyPlot.jl/blob/master/.travis.yml) ends up using `apt` to install, so that seems like it might be the most straightforward solution.

The OS X CI checks were already there in the .travis.yml file, so I didn't take them out without discussing it first. But you're right that the package shouldn't need to be checked on OS X as well as Linux.

You were right about Manifest.toml, so I've removed it. Some popular projects (like Flux.jl) seem to include, but others don't, so it seems like it's superfluous to include.

**Pull request merged**
